# Generated by Django 5.1.7 on 2025-03-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
